@startuml

title Diagrama de clases ejercicio Puerto


package domain{

	class Puerto {
	-List<Alquiler> alquileres
	-List<Amarre> amarres
	-alquileresActivos = 0
	-alquileresFinalizados = 0
	-CANTIDAD_AMARRES
	
	-mostrarAmarres()
	-mostrarEstadoAmarre()
		-amarresLibres(true)
		-amarresOcupados(false)
	-totalAmarres()
	
	-iniciarAlquiler()
	-mostrarAlquileres()
	-finalizarAlquiler()
	
	-alquileresActivos()
	-alquileresFinalizados()
	-totalAlquileres()
	-mostrarAlquileresNoFinalizados()
	}
		note top of Puerto
	*CANTIDAD_AMARRES: Es una constante 
	que servira para definir cuantos 
	amarres crear al momento de la 
	creacion del puerto
		end note
	
		note top of Puerto
	*alquileresActivos y alquileresFinalizados:
	serviran de contadores, inicializados en 0
		end note
	

	class Alquiler {
	-idAlquiler
	-Cliente cliente
	-Amarre amarre
	-Barco barco
	-alquilerDiaInicial = 1
	-alquilerDiaFinal = null
	-totalAPagar
	-nextValueId = 100L
	-nextValuePosicion = 1
	
	-getIdAmarre()
	-getPrecioBarco()
	-getPosicionAmarre()
	
	-mostrarAlquileres()
	-estaFinalizado()
	}
	
		note bottom of Alquiler
	*alquilerDiaInicial y alquilerDiaFinal: 
	seteados inicialmente por default
	*nextValueAlquiler: auxiliar para increementar
	idAlquiler en cada instancia
		end note
	

	class Amarre {
	+id = 001L
	+posicion = 0
	+estaLibre
	+nextValueId = 100L
	+nextValuePosicion = 1
	
	-ocuparAmarre()
	-liberarAmarre()
	}
	
		note bottom of Amarre
	*nextValueId y nextValuePosicion:
	auxiliares para increementar
	posicion y id en cada instancia
		end note


	class Cliente {
	+String nombre
	+String apellido
	+String dni
	
	-getCliente()
	}
	

	abstract class Barco {
	+matricula
	+eslora
	+anioFabricacion
	
	-getPrecio()
	-mostrarBarco()
	}
	
	
	class Velero{
	-final PRECIO
	
	-getPrecio()
	}
	
	
	class Yate{
	-final PRECIO
	
	-getPrecio()
	}
	
	
	class Catamaran{
	-final PRECIO
	
	-getPrecio()
	}
	
	
	class Lancha{
	-final PRECIO
	
	-getPrecio()
	}
	
	
	class MotoAcuatica{
	-final PRECIO
	
	-getPrecio()
	}
	
	
	class Anfibio{
	-final PRECIO
	
	-cantidadRuedas
	-velocidadTierra
	
	-getPrecio()
	
	-mostrarRuedas()
	-mostrarVelocidadTierra()
	}
	
	
	interface InterfaceAnfibio{
	-mostrarRuedas()
	-mostrarVelocidadTierra()
	-mostrarAnfibio()
	}
}

	package test{
	class PuertotTest
	}
	
	
	
Puerto --> Alquiler
Alquiler -left-> Amarre
Alquiler -right-> Cliente
Alquiler -down-> Barco

Barco <|-- Velero
Barco <|-- Yate
Barco <|-- Catamaran
Barco <|-- Lancha
Barco <|-right- Anfibio
Barco <|-- MotoAcuatica

InterfaceAnfibio <|.. Anfibio



@enduml